In [35]:
import matplotlib.pyplot as plt
import numpy as np
import warnings
warnings.simplefilter("ignore",DeprecationWarning)
arr=np.array([10,20,30,40,50])
arr_stand=(arr-arr.mean())/(arr.std())
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit_transform(arr.reshape(-1,1))
scaler.fit_transform(arr.reshape(-1,1))
from sklearn.preprocessing import MinMaxScaler
min_max=MinMaxScaler()
min_max.fit_transform(arr.reshape(-1,1))
from pandas.core import frame
import pandas as pd
from pandas import DataFrame
data={'name':['rex','peter','sam'],'age':[1,95,22],'height':[20,180,160],'weight':[75,55,90],'bp':[90,80,120]}
frame=DataFrame(data)
print(frame)
frame = DataFrame(data)
print(frame)
frame.to_csv('patient_data.csv', index=False)
df = pd.read_csv('patient_data.csv')
print(df)
frame2 = df[['age', 'bp', 'height', 'weight']]
print(frame2)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(frame2)
scaled = scaler.transform(frame2)
print(scaled)
print(scaled.mean(axis=0))
print(scaled.std(axis=0))
frame3=df[['age','bp','height','weight']]
min_max.fit(frame3)
scaled2 = min_max.transform(frame3)
print(scaled2)
print("mean : %s " % scaled2.mean(axis=0))
print("standard deviation : %s " % scaled2.std(axis=0))
from sklearn.feature_selection import VarianceThreshold
sel = VarianceThreshold(threshold=(.5 * (1 - .9)))
useful_features1 = sel.fit_transform(scaled)
print('Useful feature values based on StandardScaler\n')
print(useful_features1)
useful_features2=sel.fit_transform(scaled2)
print ('\nUseful feature values based on MinMaxScaler')
print(useful_features2)



    name  age  height  weight   bp
0    rex    1      20      75   90
1  peter   95     180      55   80
2    sam   22     160      90  120
    name  age  height  weight   bp
0    rex    1      20      75   90
1  peter   95     180      55   80
2    sam   22     160      90  120
    name  age  height  weight   bp
0    rex    1      20      75   90
1  peter   95     180      55   80
2    sam   22     160      90  120
   age   bp  height  weight
0    1   90      20      75
1   95   80     180      55
2   22  120     160      90
[[-0.95155127 -0.39223227 -1.40487872  0.11624764]
 [ 1.38181793 -0.98058068  0.84292723 -1.27872403]
 [-0.43026666  1.37281295  0.56195149  1.16247639]]
[-7.40148683e-17 -2.96059473e-16  0.00000000e+00  2.96059473e-16]
[1. 1. 1. 1.]
[[0.         0.25       0.         0.57142857]
 [1.         0.         1.         0.        ]
 [0.22340426 1.         0.875      1.        ]]
mean : [0.40780142 0.41666667 0.625      0.52380952] 
standard deviation : [0.42856484 0.424